Coating Protection for M1, M2 and M3
pcdshub/HOMS_XRT pull request #23
Opened 2021-03-03 04:17 UTC by ghalym

2021-03-03 17:22 UTC, slacAWallace requested changes
Using scaled encoder values seems risky. Am I over thinking this?

2021-03-03 17:22 UTC, slacAWallace commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +		rFirstCoatingPosition:= -5,
Using real units makes me very uncomfortable. Is there a reason raw encoder counts aren't being used here?

2021-03-03 17:22 UTC, slacAWallace commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +//With M2 the same coating has different bit masks depending on the pitch
Holy moly, that's cool.

2021-03-03 17:22 UTC, slacAWallace commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +		fbM2.nFirstCoatingBitmask:= 2#1111_1111_1111_1111;
Extra indent.

2021-03-03 17:55 UTC, ghalym commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +		rFirstCoatingPosition:= -5,
I don't have the raw encoder values that corresponds to these real values.
I thought I will have more time to get them with the next upgrade.
Please advise.

2021-03-03 18:02 UTC, ghalym commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +		fbM2.nFirstCoatingBitmask:= 2#1111_1111_1111_1111;
Fixed.

2021-03-03 18:37 UTC, nrwslac commented on HOMS_XRT/HOMS_XRT_PLC/POUs/FB_MirrorCoatingProtection.TcPOU
> +	ffSecondCoating.i_Desc := CONCAT(sFirstCoatingType, ' mirror coating incompatible with beam photon energy');
FirstCoatingtype with SecondCoating.i_Desc, intentional?

2021-03-03 18:39 UTC, nrwslac commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +	bMirrorIn := (HOMS2_XGantry.PAxis.stStatus.rActPosition > -5) , // according to confluence -6 is nominal out position
mirror1 with HOMS2 gantry.

2021-03-03 18:59 UTC, ghalym commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +	bMirrorIn := (HOMS2_XGantry.PAxis.stStatus.rActPosition > -5) , // according to confluence -6 is nominal out position
Fixed. Thanks!

2021-03-03 19:01 UTC, ghalym commented on HOMS_XRT/HOMS_XRT_PLC/POUs/FB_MirrorCoatingProtection.TcPOU
> +	ffSecondCoating.i_Desc := CONCAT(sFirstCoatingType, ' mirror coating incompatible with beam photon energy');
Fixed.

2021-03-04 04:32 UTC, slacAWallace commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +		rFirstCoatingPosition:= -5,
OK, considering the timeframe, we can stick with this. Let's fix at the next available opportunity after we have some time to gather the encoder counts and verify them.

2021-03-04 22:19 UTC, jsheppard95 approved these changes
No issues with this PR, just clarifying questions and some extra context for the XRT/FEE differences.

2021-03-04 22:19 UTC, jsheppard95 commented on HOMS_XRT/iocBoot/ioc-HOMS-XRT-PLC/Makefile
> +IOC_TOP=/reg/g/pcds/epics/ioc/common/ads-ioc/0.3.1
The previous IOC is running on the XRT `iocmanager`:

```
[sheppard@psbuild-rhel7-01  ioc-xrt-homs]$ grep_ioc homs xrt
 {id:'ioc-xrt-homs', host: 'ioc-xrt-mxtmirror', port: 39010, dir: 'ioc/fee/homs/R1.2.6', alias: 'HOMS Motion',
  history: ['/reg/g/pcds/package/epics/3.14-dev/ioc/common/homs/current']},
```
from the directory `/reg/g/pcds/epics/ioc/fee/homs/R1.2.6/iocBoot/ioc-xrt-homs`. This includes all of the Modbus stuff, but the work in this PR shouldn't affect any of that so this IOC should just start back up.

2021-03-04 22:26 UTC, slacAWallace commented on HOMS_XRT/HOMS_XRT_PLC/POUs/FB_MirrorCoatingProtection.TcPOU
> +IF (bMirrorIn) THEN
The mapping is captured in a PMPS global constant. 
Since it's a bitmask, the allowed range will rarely = the current eV range. The allowed range usually looks like 0000_1110_1111_0000 and the current 0000_0000_0010_0000. Someday in the future it may look like 0000_0010_0100_0000 in modes where we run multiple energies or account for harmonics, hence the use of bitmasks instead of arrays, or just a single scalar.

2021-03-04 22:27 UTC, slacAWallace commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +   fbM1 : FB_MirrorCoatingProtection := (
Since we didn't have the raw encoder counts, Maggie had to use REALs. Also the logic here might be a bit more complex than the simple two coating system. Especially with the pitch logic being employed. Maggie might have more to say.

2021-03-04 22:33 UTC, slacAWallace commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +HOMS1_Pitch.Stepper.rStepperDmovRange := 15;
I am ashamed and proud to say that these values were rediscovered by reading my past blog posts, which mentioned that I had "squirrelled" away these settings in a script in the iocBoot directory. A professional would have baked them in using autosave, or the st.cmd, or the PLC (retains). etc.

2021-03-04 22:35 UTC, slacAWallace approved these changes

2021-03-04 22:38 UTC, jsheppard95 commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +HOMS1_Pitch.Stepper.rStepperDmovRange := 15;
Yup, and I'm ashamed and proud to say I just found the script in the iocBoot directory: `/reg/g/pcds/epics/ioc/fee/homs/R1.2.6/iocBoot/ioc-xrt-homs/restoreDeadbands.sh`. I completely missed it during the pre-run 18 checkout...

2021-03-04 22:55 UTC, slacAWallace commented
Can anyone really be expected to find that though?

From: Jackson Sheppard <notifications@github.com>
Sent: Thursday, March 4, 2021 2:39 PM
To: pcdshub/HOMS_XRT <HOMS_XRT@noreply.github.com>
Cc: Wallace, Alex <awallace@slac.stanford.edu>; Review requested <review_requested@noreply.github.com>
Subject: Re: [pcdshub/HOMS_XRT] Coating Protection for M1, M2 and M3 (#23)


@jsheppard95 commented on this pull request.

________________________________

In HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU<https://github.com/pcdshub/HOMS_XRT/pull/23#discussion_r587878596>:

> @@ -191,6 +200,10 @@ HOMS1_Pitch.Piezo.stPIParams.fKp := 0.001;

 HOMS1_Pitch.Piezo.stPIParams.tTn := T#500MS;

 HOMS1_Pitch.Piezo.stPIParams.fOutMaxLimit := 1;

 HOMS1_Pitch.Piezo.stPIParams.fOutMinLimit := -1;

+

+// Initialize deadband settings

+HOMS1_Pitch.Stepper.rStepperDmovRange := 15;

Yup, and I'm ashamed and proud to say I just found the script in the iocBoot directory: /reg/g/pcds/epics/ioc/fee/homs/R1.2.6/iocBoot/ioc-xrt-homs/restoreDeadbands.sh. I completely missed it during the pre-run 18 checkout...

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/pcdshub/HOMS_XRT/pull/23#discussion_r587878596>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AFY4XUBZWHMMHKDSWCFDL6TTCADYDANCNFSM4YQNYG2Q>.

2021-03-05 18:21 UTC, nrwslac commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +IF (HOMS2_Pitch.diEncCnt < 9616668 ) THEN//(HOMS2_Pitch.Stepper.stStatus.rActPosition < -400 ) THEN //MFX
instead of these magic numbers, can we create a variable pitchLowLimit

2021-03-05 18:22 UTC, nrwslac commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +ELSIF (HOMS2_Pitch.diEncCnt > 10129409 ) THEN// (HOMS2_Pitch.Stepper.stStatus.rActPosition > 600) THEN //MEC
magic number, change to pitchM2HighLimit

2021-03-05 18:24 UTC, nrwslac commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +	//{attribute 'TcLinkTo' := 	'.Gantry.diEncCnt	:=	TIIB[M1-Y1 (Elmo Drive)]^Inputs^Position actual value'}
delete?

2021-03-05 18:24 UTC, nrwslac commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +	//{attribute 'TcLinkTo' := 	'.Gantry.diEncCnt	:=	TIIB[M2-Y1 (Elmo Drive)]^Inputs^Position actual value'}
do we need these?

2021-03-05 18:24 UTC, nrwslac commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +//	{attribute 'TcLinkTo' := 	'.Gantry.diEncCnt	:=	TIIB[M3-Y1 (Elmo Drive)]^Inputs^Position actual value'}
is this in use?

2021-03-08 19:35 UTC, jsheppard95 commented on HOMS_XRT/HOMS_XRT_PLC/POUs/FB_MirrorCoatingProtection.TcPOU
> +IF (bMirrorIn) THEN
That makes sense, but I was actually wondering why we have the line:
```
ffFirstCoating.i_xOK := (neVRange AND nFirstCoatingBitmask) = neVRange;
```
as opposed to simply this?
```
ffFirstCoating.i_xOK := (nFirstCoatingBitmask = neVRange);
```

2021-03-08 19:42 UTC, ghalym commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +   fbM1 : FB_MirrorCoatingProtection := (
@jsheppard95 I didn't use the Lib's two coating protection since it used an upper boundary and a lower boundary. In the case of the XRT, as per requirements we had specific set positions with +/- deltas for each coating.

2021-03-08 19:44 UTC, slacAWallace commented on HOMS_XRT/HOMS_XRT_PLC/POUs/FB_MirrorCoatingProtection.TcPOU
> +IF (bMirrorIn) THEN
Because first coating bitmask will look like:
1111_1111_0000_0000
and neVRange will look like:
0000_0000_0001_0000

They will almost never be equal. So we have to do some kind of operation to make sure the neVRange is not outside of nFirstCoatingBitmask.

2021-03-08 19:47 UTC, jsheppard95 commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +	//{attribute 'TcLinkTo' := 	'.Gantry.diEncCnt	:=	TIIB[M1-Y1 (Elmo Drive)]^Inputs^Position actual value'}
Yes this is no longer used. This would've been to link the raw encoder count of the Y master axis, but that's instead linked to an instance within `GVL_Devices` (though it is linked by hand as opposed to automatically with the pragma). The PLC variable that the raw count is actually linked to is `GVL_Devices.HOMS1_YGantry.PAxis.diEncCnt`, and similarly for the secondary axes and the X gantry/Pitch.

2021-03-08 20:00 UTC, nrwslac approved these changes
looks ready to merge!

2021-03-08 20:03 UTC, jsheppard95 commented on HOMS_XRT/HOMS_XRT_PLC/POUs/FB_MirrorCoatingProtection.TcPOU
> +IF (bMirrorIn) THEN
I see, reading the Wikipedia entry on bit masks is making that a bit more clear. I was thinking of these still as arrays with essentially the allowed energy values, and we were simply checking for equality as:
```
Result = (array1 and array2) == array1
```
But really there are some bit operations happening...

2021-03-08 20:57 UTC, merged

2021-03-08 21:10 UTC, jsheppard95 commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +	//{attribute 'TcLinkTo' := 	'.Gantry.diEncCnt	:=	TIIB[M2-Y1 (Elmo Drive)]^Inputs^Position actual value'}
Not needed either, we can get rid of all the unused code in the next PR

2021-03-08 21:10 UTC, jsheppard95 commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +//	{attribute 'TcLinkTo' := 	'.Gantry.diEncCnt	:=	TIIB[M3-Y1 (Elmo Drive)]^Inputs^Position actual value'}
Nope!

2021-03-08 21:15 UTC, jsheppard95 commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +ELSIF (HOMS2_Pitch.diEncCnt > 10129409 ) THEN// (HOMS2_Pitch.Stepper.stStatus.rActPosition > 600) THEN //MEC
That seems reasonable, but if so they should be in a `GVL_Constants` so that they cannot be easily changed by logging into the PLC.