Xrt m2 upgrade
pcdshub/HOMS_XRT pull request #34
Opened 2021-08-06 20:09 UTC by nrwslac

Controls software to support the removal of ELMO hardware and installation of Beckhoff hardware. Modbus no longer active.

2021-08-09 18:39 UTC, klauer reviewed
Partial review, things mostly looking good so far. Needs a bit more cleanup on removing old, unused code.

2021-08-09 18:39 UTC, klauer commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +MR1L4.fbRunHOMS(stYup:=M7,
Reminder to reviewers: FB_RunHOMS comes from lcls-twincat-optics (https://pcdshub.github.io/lcls-twincat-optics/v0.2.1/lcls-twincat-optics_lcls_twincat_optics_plc_source.html#fb-runhoms)

2021-08-09 18:39 UTC, klauer commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +	MR1L4 : DUT_HOMS;
Reminder to reviewers: DUT_HOMS comes from lcls-twincat-optics: https://pcdshub.github.io/lcls-twincat-optics/v0.2.1/lcls-twincat-optics_lcls_twincat_optics_plc_source.html#dut-homs

2021-08-09 19:17 UTC, ZLLentz commented
After this is all done, it's probably finally time to rename the repo/project to match the others. Doesn't have to be during this PR.

2021-08-12 17:16 UTC, nrwslac commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +bXRT_M2_IN  := Main.MR1L4.fbRunHOMS.stXupEnc.Count < 25490840;
I'm not sure why magic values are ever okay.

2021-08-16 16:36 UTC, klauer commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +bXRT_M2_IN  := Main.MR1L4.fbRunHOMS.stXupEnc.Count < 25490840;
They aren't, you are 100% correct! 😁

2021-09-10 18:45 UTC, klauer requested changes
I think the core of this looks good, but I'd like to see all of the old references to old code cleaned up before merging this back in. 

It's best to do these sorts of things at refactor time rather than down the line, since it will only be more confusing then.

2021-09-10 18:45 UTC, klauer commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +//rtInitParams(CLK:=gFirstPass);
All of these commented and no-longer-valid/relevant blocks need to go away; they make this more difficult to review or just read.

2021-09-10 18:45 UTC, klauer commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +    rCurrentEncoderPosition := Main.nEncCntYupMR1L4,
`Main.nEncCntYupMR1L4` is
```
nEncCntYupMR1L4 := ULINT_TO_UDINT(MR1L4.fbRunHOMS.stYupEnc.Count);
```
but you use `Main.MR1L4.fbRunHOMS.stXupEnc.Count` directly above? Any reason for not being consistent between the two?

2021-09-10 18:45 UTC, klauer commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +	fMaxXRMSErrorMR1L4 : LREAL;
Do these not go to EPICS? Are we just using them to look at in TwinCAT when logging in... ?

2021-09-10 18:45 UTC, klauer commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +	//XRTM2PitchControl	    :	FB_PitchControlOld;
More old references to remove

2021-09-10 19:15 UTC, nrwslac commented on HOMS_XRT/HOMS_XRT_PLC/POUs/PRG_CoatingProtection.TcPOU
> +    rCurrentEncoderPosition := Main.nEncCntYupMR1L4,
looks equivalent, changes made.

2021-09-10 19:15 UTC, nrwslac commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +//rtInitParams(CLK:=gFirstPass);
deleted more commented out code

2021-09-10 19:17 UTC, nrwslac commented on HOMS_XRT/HOMS_XRT_PLC/POUs/MAIN.TcPOU
> +	fMaxXRMSErrorMR1L4 : LREAL;
not sure what these are used for, theres a lot of testing/lingering code in this project that my have been future plans or previous test software.

2021-09-10 23:33 UTC, klauer approved these changes
Looks much better - nice work @nrwslac 👍

2021-09-14 20:47 UTC, merged